# Generated by Django 6.1 on 2026-09-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subscriptionplan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
