# Generated by Django 6.1 on 2026-09-30 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0042_alter_examination_question_paper_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='exams.topic'),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
