# Generated by Django 6.1 on 2026-09-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0043_examination_topic_practicesession_shuffle_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='mode',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('timed', 'Timed'), ('study', 'Study'), ('revision', 'Revision'), ('saved', 'Saved Questions'), ('daily', 'Daily Practice')], default='flexible', max_length=20),
        ),
    ]
