# Generated by Django 6.1 on 2026-09-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0049_extend_examination_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('all', 'All Types'), ('topicwise', 'Topicwise Test'), ('objective', 'Objective Exam'), ('subjective', 'Subjective Exam')], default='objective', help_text='Primary classification: topicwise, objective, subjective, or all', max_length=20),
        ),
        migrations.AlterField(
            model_name='examination',
            name='evaluation_type',
            field=models.CharField(choices=[('admin', 'Admin Evaluation'), ('manual', 'Manual Examiner Evaluation'), ('ai', 'AI Evaluation'), ('ai_assisted', 'AI-Assisted Evaluation'), ('hybrid', 'Hybrid Evaluation')], default='admin', max_length=20),
        ),
    ]
