# Generated by Django 6.1 on 2026-09-30 15:35

import core.upload_validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_canonical_course_hierarchy_data'),
        ('exams', '0050_examschedule_exam_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectiveQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(max_length=500, upload_to='subjective_exams/question_sets/%Y/%m/', validators=[core.upload_validators.validate_document_size_20mb, django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'webp']), core.upload_validators.validate_pdf_upload])),
                ('duration_minutes', models.PositiveIntegerField(default=180)),
                ('total_marks', models.FloatField(default=100)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='inactive', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjective_question_sets', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjective_question_sets', to=settings.AUTH_USER_MODEL)),
                ('exam_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjective_question_sets', to='exams.examcategory')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjective_question_sets', to='exams.exam')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjective_question_sets', to='exams.subject')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='subjective_question_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='exams.subjectivequestionset'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestionset',
            index=models.Index(fields=['status', 'exam_category', 'level'], name='exams_subje_status_002cee_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectivequestionset',
            index=models.Index(fields=['status', 'subject'], name='exams_subje_status_53bf90_idx'),
        ),
    ]
