# Generated by Django 6.1 on 2026-10-01 02:20

import django.db.models.deletion
from django.db import migrations, models


def backfill_question_exam_and_category(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    for q in Question.objects.filter(subject__isnull=False).select_related('subject__paper__exam__category'):
        try:
            if q.subject and q.subject.paper and q.subject.paper.exam:
                q.exam_id = q.subject.paper.exam_id
                q.category_id = q.subject.paper.exam.category_id
                q.save(update_fields=['exam', 'category'])
        except Exception:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0051_subjectivequestionset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Academic Category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.examcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, help_text='Level / Position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10, null=True),
        ),
        migrations.RunPython(backfill_question_exam_and_category, migrations.RunPython.noop),
    ]
