# Generated by Django 6.1 on 2026-10-01 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_csvimport_chapter_csvimport_subject'),
        ('exams', '0052_question_category_question_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.examcategory'),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csv_imports', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='csvimport',
            name='difficulty',
            field=models.CharField(blank=True, default='medium', max_length=10, null=True),
        ),
    ]
