# Generated by Django 6.1 on 2026-10-01 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_csvimport_category_csvimport_exam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('backup_type', models.CharField(choices=[('full', 'Full Database Backup'), ('pre_restore', 'Pre-Restore Safety Snapshot'), ('manual', 'Manual Database Backup'), ('scheduled', 'Scheduled Automatic Backup')], db_index=True, default='full', max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'Creating Backup...'), ('validating', 'Validating...'), ('verified', 'Verified'), ('failed', 'Failed'), ('corrupted', 'Corrupted')], db_index=True, default='in_progress', max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('record_counts', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.CharField(blank=True, max_length=100)),
                ('db_engine', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_message', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_index=True, max_length=50)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=100)),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('deleted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('is_restored', models.BooleanField(db_index=True, default=False)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('is_permanent_deleted', models.BooleanField(db_index=True, default=False)),
                ('permanent_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False, help_text='True if historical records depend on this item, preventing permanent deletion')),
                ('protection_reasons', models.JSONField(blank=True, default=list)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_trash_items', to=settings.AUTH_USER_MODEL)),
                ('permanent_deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanently_deleted_trash_items', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_trash_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
                'indexes': [models.Index(fields=['is_restored', 'is_permanent_deleted', 'deleted_at'], name='administrat_is_rest_97ab03_idx'), models.Index(fields=['app_label', 'model_name', 'object_id'], name='administrat_app_lab_1d5a61_idx')],
            },
        ),
    ]
