# Generated by Django 6.1 on 2026-10-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_databasebackup_trashitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='is_protected',
            field=models.BooleanField(db_index=True, default=False, help_text='Protected backups cannot be auto-purged by retention'),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='r2_etag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='r2_uploaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='r2_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='restore_status',
            field=models.CharField(blank=True, default='not_restored', max_length=30),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='retention_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='storage_backend',
            field=models.CharField(choices=[('local', 'Local Storage'), ('cloudflare_r2', 'Cloudflare R2'), ('dual', 'Local & Cloudflare R2')], db_index=True, default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='storage_key',
            field=models.CharField(blank=True, help_text='R2 S3-compatible object key', max_length=500),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Creating Backup...'), ('uploading', 'Uploading to Cloudflare R2...'), ('validating', 'Validating Archive...'), ('verified', 'Verified'), ('failed', 'Failed'), ('corrupted', 'Corrupted'), ('expired', 'Expired / Cleaned')], db_index=True, default='in_progress', max_length=20),
        ),
    ]
